# Test the ability of a docker container to write to the terminal.  
# Docker will also create a logfile when this container is run, see it with:
# docker logs <CONTAINER ID>

# use this image
FROM ubuntu

# do these things
CMD echo "Hello World!"
